### ISSUE TITLE
Mysql / Mariadb support ?

### ISSUE THREAD

**Issue by accforgithubtest** [vigimite/aqueducts#36]
Is Mysql / Mariadb supported ? or is the source and destinations limited to postgres ?

**Comment by vigimite** [comment]
Hi sorry for the late response, i don't seem to get notified on issue creation...

Yes, both Mysql and Mariadb support connection via ODBC so you would just need to set up your ODBC driver manager correctly and then you just need the right connection string: https://www.connectionstrings.com/mysql/

**Comment by accforgithubtest** [comment]
Thanks for the confirmation !
